chat/urls.py
from django.conf.urls import patterns, url, include
from chat import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<chat_room_id>\d+)/$', views.chat_room, name='room'),
    url(r'^long-poll/(?P<chat_room_id>\d+)/$', views.longpoll_chat_room, name='logpoll_room'),
)

kitty/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('frontsite.urls', namespace='frontsite')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^pdf/', include('pdf.urls', namespace='pdf')),
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

pdf/urls.py
from django.conf.urls import patterns, url, include
from pdf import views
from django.contrib.auth.views import logout

urlpatterns = patterns('',
   url(r'^test$', views.generate, name='view'),
   url(r'^export/(?P<rhyme_id>\d+)$', views.ExporterPDFView.as_view(), name='index'),
   url(r'^export/(?P<context>all)$', views.ExporterPDFView.as_view(), name='all'),
   url(r'^export/(?P<context>favorite)$', views.ExporterPDFView.as_view(), name='favorite'),
   url(r'^export/(?P<context>[\w\W]+)$', views.ExporterPDFView.as_view(), name='favorite'),
)

chat/models.py
from django.contrib import admin
from django.db import models

class ChatRoom(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

admin.site.register(ChatRoom)

chat/views.py
import socket
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from chat.models import ChatRoom
from django.contrib.sessions.backends.db import SessionStore

def index(request):
    context = {
        'chats': ChatRoom.objects.order_by('name')[:5]
    }
    return render(request, 'chat/index.html', context)

def chat_room(request, chat_room_id):
    context = {
        'chat': get_object_or_404(ChatRoom, pk=chat_room_id)
    }
    return render(request, 'chat/chat_room.html', context)

def longpoll_chat_room(request, chat_room_id):
    context = {
        'chat': get_object_or_404(ChatRoom, pk=chat_room_id)
    }
    return render(request, 'chat/longpoll_chat_room.html', context)

chat/templates/chat/chat.html
{% load staticfiles %}

<div class="row well">
    <div class="col-md-8">
        {#<h4>{{ chat.name }}</h4>#}


        <ul id="chat-tabs" class="nav nav-tabs">
            <li class="active"><a href="#main-chat" data-toggle="tab">Czat</a></li>
        </ul>
        <div id="chat-panel" class="tab-content">
            <div class="tab-pane fade in active" id="main-chat">
                <div class="message-list" id="message_list"></div>
                <div class="controls row">
                    <div class="col-md-8">
                        <input class="form-control" id="send-text" type="text" />
                    </div>
                    <div class="col-md-4">
                        <button class="btn btn-info" id="send-button">Wyślij <i class="fa fa-send"></i></button>
                    </div>
                </div>
            </div>
        </div>
        <!--<div class="controls row">
            <div class="col-md-8">
                <input class="form-control" id="send-text" type="text" />
            </div>
            <div class="col-md-4">
                <button class="btn btn-info" id="send-button">Wyślij <i class="fa fa-send"></i></button>
            </div>
        </div>-->
    </div>

    <div clas="col-md-4">
        <div class="users">
            <ul class="list-unstyled ">

            </ul>
        </div>
        <div class="button-collapse pull-right"><button class="btn fa fa-angle-double-right"></button></div>
        <div class="pull-right"><button id="sound-button" class="btn fa fa-music"></button></div>
        <h5 id="author">{{ request.user }}</h5>
        <h6 id="connection_status"></h6>
        <button id="connect-button" class="btn btn-xs btn-success">Połącz</button>
        <button id="disconnect-button" class="btn btn-xs btn-danger">Rozłącz</button>
        <audio src="{% static 'chat/sound.mp3' %}"></audio>
    </div>
</div>


<div name="chat-key" style="display:none">{{ request.session.session_key }}</div>

chat/templates/chat/chat_room.html
{% extends 'chat/layout.html' %}

{% block body %}
    {% include "chat/chat.html" %}
{% endblock %}

chat/templates/chat/index.html
{% extends 'chat/layout.html' %}
{% block body %}
    {% if chats %}
        {% for chat in chats %}
            <ul>
                <li><a href="{% url 'chat:room' chat.id %}">{{ chat.name }}</a></li>
            </ul>
        {% endfor %}
    {% else %}
        Brak chatów.
    {% endif %}


{% endblock %}

chat/templates/chat/layout.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
    <head>

        {% block stylesheets %}
            <link type="text/css" href="{% static 'chat/main.css' %}" rel="stylesheet" />
        {% endblock %}
        {% block stylesheets-custom %}{% endblock %}
    </head>
<body>
{% block body %}

{% endblock %}
 </body>
{% block footer %}

{% endblock %}

{% block javascripts %}
<script type="text/javascript" src="{% static 'chat/jquery-2.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'chat/jquery-config.js' %}"></script>
<script type="text/javascript" src="{% static 'chat/client.js' %}"></script>
{% endblock %}
{% block javascript-custom %}{% endblock %}

</html>

chat/templates/chat/longpoll_chat_room.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>{{ chat.name }}</h1>
    <div id="message list"></div>
</body>
</html>