frontsite/urls.py
from django.conf.urls import patterns, url, include
from frontsite import views
from django.contrib.auth.views import logout

urlpatterns = patterns('',
   url(r'^$', views.Rhyme.as_view(), name='index'),
   url(r'^map-order$', views.map_order, name='map_order'),
   url(r'^voters/(?P<rhyme_id>\d+)/$', views.voters, name='voters'),
   url(r'^count-author-rhyme-votes/$', views.count_author_rhyme_votes, name='count_author_rhyme_votes'),
   url(r'^comment-unread/$', views.comments_unread, name='comment_unread'),
   url(r'^comment-mark-as-read/(?P<rhyme_id>)/$', views.comments_mark_as_read, name='comment_mark_as_read'),
   url(r'^comment-mark-as-read/json$', views.comments_mark_as_read_json, name='comment_mark_as_read_json'),
   url(r'^comment-show/(?P<rhyme_id>\d+)$', views.comment_show, name='comment_show'),
   url(r'^category-(?P<category_id>\d+)$', views.Rhyme.as_view(), name='rhymes_by_category'),
   url(r'^search-rhymes$', views.Rhyme.as_view(), name='rhymes_search'),
   url(r'^typehead-rhymes/(?P<query>[\w\W]+).json$', views.typehead_search, name='typehead_search'),
   url(r'^delete-comment/(?P<id>\d+)$', views.delete_comment, name='delete_comment'),
   url(r'^rhyme-view/(?P<id>\d+)$', views.rhyme_view, name='rhyme_view'),
   url(r'^most-popular/$', views.most_popular, name='popular'),
   url(r'^random/$', views.random, name='random'),
   url(r'^stored/$', views.stored, name='stored'),
   url(r'^rhyme-store/(?P<id>\d+)$', views.rhyme_store, name='rhyme-store'),
   url(r'^rhyme-unstore/(?P<id>\d+)$', views.rhyme_unstore, name='rhyme-unstore'),
   url(r'^rhyme/(?P<id>\d+)/(?P<delete>\w+)?$', views.Rhyme.as_view(), name='rhyme_detail'),
   url(r'^vote-rhyme/(?P<rhyme_id>\d+)$', views.vote_rhyme, name='vote-rhyme'),
   url(r'^avatar/$', views.avatar, name='avatar'),
   url(r'^show-avatar/(?P<path>.+)$', views.show_avatar, name='show-avatar'),
   url(r'^vote/(?P<profile_id>\d+)$', views.vote, name='vote'),
   url(r'^category$', views.Category.as_view(), name='category'),
   url(r'^category/(?P<id>\d+)/(?P<delete>\w+)?$', views.Category.as_view(), name='category_detail'),
   url(r'^user/(?P<id>\d+)$', views.User.as_view(), name='user'),
   url(r'^user/(?P<id>\d+).json$', views.User.as_view(), name='user_json'),
   url(r'^users/$', views.get_all_users, name='all_users'),
   url(r'^token$', views.token, name='token'),
   url(r'^locale/(?P<lang>[a-zA-Z_]+)', views.Locale.as_view(), name='locale'),
   url(r'^login$', views.Login.as_view(), name='login'),
   url(r'^registration$', views.Registration.as_view(), name='registration'),
   url(r'^logout$', views.Logout.as_view(), name='logout'),
)

kitty/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('frontsite.urls', namespace='frontsite')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^pdf/', include('pdf.urls', namespace='pdf')),
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

pdf/urls.py
from django.conf.urls import patterns, url, include
from pdf import views
from django.contrib.auth.views import logout

urlpatterns = patterns('',
   url(r'^test$', views.generate, name='view'),
   url(r'^export/(?P<rhyme_id>\d+)$', views.ExporterPDFView.as_view(), name='index'),
   url(r'^export/(?P<context>all)$', views.ExporterPDFView.as_view(), name='all'),
   url(r'^export/(?P<context>favorite)$', views.ExporterPDFView.as_view(), name='favorite'),
   url(r'^export/(?P<context>[\w\W]+)$', views.ExporterPDFView.as_view(), name='favorite'),
)

frontsite/models.py
from django.contrib import auth
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(auth.models.User, related_name='profile')

class Avatar(models.Model):
    name = models.CharField(max_length=50)
    path = models.CharField(max_length=255)
    profile = models.OneToOneField(UserProfile, related_name='avatar')

class VoteUserProfile(models.Model):
    user_profile = models.ForeignKey(UserProfile, related_name='votes')
    author = models.ForeignKey(UserProfile, related_name='voted')
    date = models.DateTimeField(auto_now_add=True, blank=True)
    strength = models.PositiveSmallIntegerField(default=1, blank=True)

class Category(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True, blank=True)
    def __unicode__(self):
        return self.title

class Rhyme(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(UserProfile, related_name='created_rhymes')
    category = models.ForeignKey(Category, null=True, blank=True, related_name='rhymes')
    public = models.BooleanField(default=True)

class VoteRhyme(models.Model):
    rhyme = models.ForeignKey(Rhyme, related_name='votes')
    author = models.ForeignKey(UserProfile, related_name='rhyme_voted')
    data = models.DateTimeField(auto_now=True, blank=True)
    strength = models.PositiveSmallIntegerField(default=1, blank=True)

class Comment(models.Model):
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True, blank=True)
    rhyme = models.ForeignKey(Rhyme, related_name='comments')
    rhyme_author_saw = models.BooleanField(default=False)
    author = models.ForeignKey(UserProfile, related_name='commented_rhymes')

class RhymeProfiles(models.Model):
    owner = models.ForeignKey(UserProfile, related_name='stored_rhymes')
    rhyme = models.ForeignKey(Rhyme, related_name='profiles')
    position_no = models.PositiveIntegerField(default=0)

frontsite/views.py
# -*- coding: utf-8 -*-
import json
from random import randint
from django.contrib import auth, messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Sum, Count, Q
from django.forms import model_to_dict
from django.utils.translation import ugettext as _
from django.utils import translation
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.core import serializers
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponse, QueryDict, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import View, FormView
from frontsite.decorators import anonymous_required, login_required
from frontsite.forms import UserForm, LoginForm, CategoryForm, AvatarForm, RhymeForm, CommentForm, UserUpdateForm
from frontsite import models
from frontsite import utils

def typehead_search(request, query):
    rhymes = models.Rhyme.objects.filter(Q(title__icontains=query) | Q(content__icontains=query))\
                .annotate(vote_strength=Sum('votes__strength'))
    if request.user.is_authenticated() and not request.user.is_staff:
        rhymes = rhymes.filter(Q(public=True) | Q(author=request.user.profile))
    if not request.user.is_authenticated():
        rhymes = rhymes.filter(public=True)
    rhymes = rhymes.order_by('-created')[:10]
    return HttpResponse(json.dumps(
        [dict(model_to_dict(item).items() + {'vote_strength': item.vote_strength}.items())  for item in rhymes]
    ))

@login_required
def count_author_rhyme_votes(request):
    author = request.user.profile
    authors_rhymes = models.Rhyme.objects.all().filter(author=author)
    strength = authors_rhymes.aggregate(vote_strength=Sum('votes__strength'))
    rhymes = authors_rhymes.annotate(vote_strength=Sum('votes__strength'))\
                .filter(vote_strength__gt=0).order_by('-vote_strength')[:10]
    data = []
    for rhyme in rhymes:
        model_items = model_to_dict(rhyme).items()
        external_items = {
            'vote_strength': rhyme.vote_strength if rhyme.vote_strength is not None else 0
        }.items()
        data.append(dict(model_items + external_items))
    return HttpResponse(json.dumps({
        'success': True,
        'strength': strength['vote_strength'],
        'data': data
    }))

@login_required
def map_order(request):
    maps = json.loads(request.body)[u'map']
    stored = models.RhymeProfiles.objects.all().filter(owner=request.user.profile)
    for map in maps:
        print map
        for store in stored:
            if int(map[u'id']) == store.id:
                store.position_no = map[u'position']
                store.save()
                messages.info(request, u'Zmieniono kolejność')
    return HttpResponse(json.dumps({
        'success': True
    }))

def voters(request, rhyme_id):
    votes = models.VoteRhyme.objects.all().filter(rhyme__id=rhyme_id)
    data = []
    for vote in votes:
        model_items = model_to_dict(vote).items()
        external_items = {
            'author_name': vote.author.user.username
        }.items()
        data.append(dict(model_items + external_items))
    return HttpResponse(json.dumps({
        'success': True,
        'data': data
    }))

def comment_show(request, rhyme_id):
    comments = models.Comment.objects.filter(rhyme_id=rhyme_id).order_by('-date')[:5]
    data = []
    for comment in comments:
        model_items = model_to_dict(comment).items()
        external_items = {
            'author_name': comment.author.user.username,
            'date': str(comment.date)
        }.items()
        data.append(dict(model_items + external_items))
    return HttpResponse(json.dumps({
        'success': True,
        'data': data
    }))

@login_required
def comments_unread(request):
    user = request.user.profile
    comments = models.Comment.objects.all().filter(rhyme_author_saw=False)\
        .filter(rhyme__author=user).exclude(author=user)[:10]
    data = []
    for comment in comments:
        model_items = model_to_dict(comment).items()
        external_items = {
            'author_name': comment.author.user.username,
            'rhyme_url': reverse('frontsite:rhyme_view', kwargs={'id': comment.rhyme.id}),
            'rhyme_title': comment.rhyme.title,
            'date': str(comment.date)
        }.items()
        data.append(dict(model_items + external_items))
    return HttpResponse(json.dumps({
        'success': True,
        'data': data,
        'count': len(comments)
    }))
def comments_mark_as_read(request, rhyme_id):
    comments = []
    if (not hasattr(request.user, 'profile')):
        return HttpResponse(json.dumps({'success': True}))
    profile = request.user.profile
    rhyme = models.Rhyme.objects.get(pk=rhyme_id)
    if rhyme.author.pk == profile.pk:
        comments = models.Comment.objects.all().filter(rhyme__id=rhyme_id)
        for comment in comments:
            comment.rhyme_author_saw = True
            comment.save()
    return HttpResponse(json.dumps({
        'success': True,
        'count': len(comments)
    }))

def comments_mark_as_read_json(request):
    profile = request.user.profile
    comments = json.loads(request.body)
    for comment_data in comments:
        comment = models.Comment.objects.get(pk=comment_data[u'id'])
        if comment.rhyme.author.pk == profile.pk:
            comment.rhyme_author_saw = True
            comment.save()

    return HttpResponse(json.dumps({
        'success': True,
        'count': len(comments)
    }))

def delete_comment(request, id):
    comment = models.Comment.objects.get(pk=id)
    rhyme = comment.rhyme
    comment.delete()
    return redirect(reverse('frontsite:rhyme_view', kwargs={'id':rhyme.id}))

def rhyme_view(request, id):
    def find_comments(rhyme):
        comments = models.Comment.objects.all().filter(rhyme=rhyme).order_by('-date')
        paginator = Paginator(comments, 10)
        page = request.GET.get('page')
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)
        return comments
    rhyme = models.Rhyme.objects.annotate(vote_strength=Sum('votes__strength')).get(pk=id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.rhyme = rhyme
            comment.author = request.user.profile
            comment.save()
            return redirect(reverse('frontsite:rhyme_view', kwargs={'id': id}))
    else:
        comments_mark_as_read(request, rhyme_id=id)
        form = CommentForm()
    return render(request, 'frontsite/rhyme_view.html', {
        'rhyme': rhyme,
        'comments': find_comments(rhyme),
        'form': form
    })

class Rhyme(FormView):
    template_name = 'frontsite/rhyme.html'

    def find_data(self, category_id=None, search=None):
        if category_id is None:
            rhymes = models.Rhyme.objects.all()\
                .annotate(vote_strength=Sum('votes__strength'))\
                .order_by('-created')
        else:
            rhymes = models.Rhyme.objects.filter(category=category_id)\
                .annotate(vote_strength=Sum('votes__strength'))\
                .order_by('-created')
        if search is not None:
            rhymes = rhymes.filter(Q(title__icontains=search) | Q(content__icontains=search))
        if self.request.user.is_authenticated() and not self.request.user.is_staff:
            rhymes = rhymes.filter(Q(public=True) | Q(author=self.request.user.profile))
        if not self.request.user.is_authenticated():
            rhymes = rhymes.filter(public=True)
        paginator = Paginator(rhymes, 10)
        page = self.request.GET.get('page')
        try:
            rhymes = paginator.page(page)
        except PageNotAnInteger:
            rhymes = paginator.page(1)
        except EmptyPage:
            rhymes = paginator.page(paginator.num_pages)
        return rhymes

    @method_decorator(login_required)
    def post(self, *args, **kwargs):
        data = self.request.POST
        if self.request.is_ajax():
            data = json.loads(self.request.body)
        form = RhymeForm(data)
        form_is_valid = form.is_valid()
        if form_is_valid:
            author = self.request.user.profile
            rhyme = form.save(commit=False)
            if self.kwargs.has_key('id'):
                rhyme.id = self.kwargs['id']
                existing_rhyme = models.Rhyme.objects.get(pk=self.kwargs['id'])
                rhyme.created = existing_rhyme.created
                author = existing_rhyme.author

            rhyme.author = author
            rhyme.save()
            if models.RhymeProfiles.objects.filter(owner=author, rhyme=rhyme).count() == 0:
                store = models.RhymeProfiles()
                (store.owner, store.rhyme) = (author, rhyme)
                store.save()
            if not self.request.is_ajax():
                return  redirect(reverse('frontsite:index'))
            if form_is_valid:
                messages.info(self.request, u'Dane zostały zaakceptowane')
        if self.request.is_ajax():
            return HttpResponse(json.dumps({
                'valid': form_is_valid,
                'errors': [(k, form.error_class.as_text(v)) for k, v in form.errors.items()]
            }))

        return render(self.request, self.template_name, {
            'form': form,
            'rhymes': self.find_data(),
            'stored': models.Rhyme.objects.filter(profiles__owner=self.request.user.profile),
        })

    def delete(self, *args, **kwargs):
        if self.kwargs.has_key('id'):

frontsite/templates/frontsite/login.html
{% extends 'layout.html' %}

{% block content %}
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <form action="?" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input class="btn btn-info center-block col-md-12" type="submit" value="logowanie">
        </form>
    </div>
    <div class="col-md-3"></div>
{% endblock %}

frontsite/templates/frontsite/logout.html
{% extends 'layout.html' %}

{% block content %}
OK
{% endblock %}

frontsite/templates/frontsite/random.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
            <div class="col-md-8 well text-center rhyme">
                {% if rhyme %}
                    <div class="well well-image">
                        <h3><a href="{% url 'frontsite:rhyme_view' rhyme.id %}">{{ rhyme.title }}</a></h3>
                        <h4><small>{{ rhyme.category.title }}</small></h4>
                    </div>
                    {{ rhyme.content|safe|linebreaks }}
                    <div class="pull-right text-success">{{ rhyme.created|date:'d M, Y' }}</div>
                    {% if request.user.is_authenticated == True %}
                        {% if rhyme in request.user.profile.stored_rhymes.all %}
                            <a href="{% url 'frontsite:rhyme-unstore' rhyme.id %}" class="pull-left btn btn-success">Wypisz się</a>
                        {% else %}
                            <a href="{% url 'frontsite:rhyme-store' rhyme.id %}" class="pull-left btn btn-success">Dodaj do ulubionych</a>
                        {% endif %}
                    {% endif %}
                {% else %}
                    <h5>Brak wierszy.</h5>
                {% endif %}
            </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

{% block javascript-custom %}
{% endblock %}

frontsite/templates/frontsite/registration.html
{% extends 'layout.html' %}

{% block content %}
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <form action="?" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input class="btn btn-info center-block col-md-12" type="submit" value="Rejestracja">
        </form>
    </div>
    <div class="col-md-3"></div>
{% endblock %}

frontsite/templates/frontsite/rhyme.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% load filters %}
{% block content %}

{% if request.user.is_authenticated == False %}
    {% include 'frontsite/components/carousel.html' %}
{% endif %}
<div class="row-fluid" ng-controller="RhymeCtrl">
{% if request.user.is_authenticated == True and request.user.id == user.id %}
    <div class="text-center">
        <button type="button" class="btn text-warning text-center fa fa-folder-open" data-toggle="collapse" data-target="#demo">
            Dodaj
        </button>
    </div>
    <div class="col-md-12 well rhyme collapse out" id="demo">
        <h3>{$ formState $}</h3>
        <form action="{$ formAction $}" role="form" method="post" ng-submit="add($event)">
            {% for field in form.visible_fields %}
                <div class="form-group {% if field.errors %}has-error{% endif %}">
                    {{ field.label_tag }}
                    {{ field|ngmodel }}
                    {% with 'errors.'|add:field.name as error_field %}
                        <div class="text-warning bg bg-danger">
                            {{ field.errors }}{$ {{ error_field }} $}
                        </div>
                    {% endwith %}
                </div>
            {% endfor %}
            {% csrf_token %}
            <div class="row">
                <button ng-click="close($event)" class="btn btn-default col-md-3">Anuluj</button>
                <input class="btn btn-success col-md-offset-1 col-md-8" type="submit" value="Zapisz" />
            </div>
        </form>
    </div>
{% endif %}
    <div class="col-md-12">
        <div><!-- {%div wrapper -->
        {% with 0 as scarfording %}
        {% for rhyme in rhymes %}
                {% if scarfording == 0 %}
                    <div class="row">
                {% endif %}
                {% ++ scarfording %}
                <div class="col-md-5 col-md-offset-1 well rhyme text-center" id="rhyme-id-{{ forloop.counter }}">
                    <!-- {# for angular -->
                    <div style="display:none" rhyme="{{ forloop.counter }}">
                        <id>{{ rhyme.id }}</id>
                        <title>{{ rhyme.title }}</title>
                        <content>{{ rhyme.content|safe }}</content>
                        <category>{{ rhyme.category.id }}</category>
                    </div>
                    <!-- angular #} -->
                    <div class="col-md-12">
                        <h2 class="text-center well-image">
                            <a href="{% url 'frontsite:rhyme_view' rhyme.id %}">
                                {{ rhyme.title }}
                            </a>
                            <small> {{ rhyme.category.title }}</small>
                            {% if rhyme.public == False %}
                                <i class="fa fa-eye-slash"></i>
                            {% endif %}
                        </h2>
                        <div class="pull-right">
                            <a href="{% url 'pdf:index' rhyme.id %}" class="btn btn-xs btn-success" target="_blank">
                                <i class="fa fa-file-pdf-o"></i>
                            </a>
                        </div>
                    </div>
                    <article>
                        {{ rhyme.content|shorter|safe|linebreaks }}
                        <a href="{% url 'frontsite:rhyme_view' rhyme.id %}">
                            cały wiersz <i class="fa fa-book"></i>
                        </a>
                    </article>
                    <hr>
                    <div class="row well-image">
                        <div class="col-md-12" ng-controller="VoteRhymeCtrl">
                            <!-- {% modal -->
                            <div class="modal fade" id="modal">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                            <h4 class="modal-title">{$ modalTitle $}</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>{$ modalBody $}</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">{$ modalCloseBtn $}</button>
                                            <button ng-click="modalConfirmAction($event)" type="button" class="btn btn-primary">{$ modalPrimaryBtn $}</button>
                                        </div>
                                    </div><!-- /.modal-content -->
                                </div><!-- /.modal-dialog -->
                            </div><!-- /.modal -->
                            <!-- modal %} -->
                            <i class="pull-right text-info">{{ rhyme.created|date:'d M, Y' }}</i>
                            <br>
                            <div class="pull-right">
                                {% if rhyme.author.user.profile.avatar.path %}
                                <img
                                        src="{% url 'frontsite:show-avatar' rhyme.author.user.profile.avatar.path|add:'tiny' %}"
                                        alt="avatar"
                                        class="img img-circle"
                                />
                                {% endif %}
                                <a href="{% url 'frontsite:user' rhyme.author.user.id %}" class="">{{ rhyme.author.user.username }}</a>
                            </div>
                            <a
                                    name="trigger-vote-{{ rhyme.id }}"
                                    ng-click="vote($event)"
                                    ng-mouseover="showVoters($event, {{ rhyme.id }})"
                                    class="btn btn-xs
                                        {% for vote in rhyme.votes.all %}
                                            {% if vote.author.id == request.user.profile.id %}
                                                text-muted
                                            {% endif %}
                                        {% endfor %}
                                    "
                                    href="{% url 'frontsite:vote-rhyme' rhyme.id %}"
                            >
                                Podoba się <i class="fa fa-plus fa-2x"> {{ rhyme.vote_strength | default_if_none:"0" }}</i>
                            </a>
                            <div id="popover-vote-{{ rhyme.id }}" class="popover">
                                <div class="popover-content">
                                    <div ng-repeat="voter in voters">
                                        <div class="row-fluid">
                                            <div class="col-md-12">
                                                {$ voter.author_name $} {$ voter.strength|addplus $}
                                            </div>
                                        </div>
                                        <hr>
                                    </div>
                                </div>
                            </div>

                            {% if request.user.is_authenticated == True %}
                                <div class="center-block" ng-controller="StoreCtrl">
                                {% if rhyme not in stored %}
                                    <a
                                            ng-click="storeChange($event, '{% url 'frontsite:rhyme-unstore' rhyme.id %}', ' Wypisz się', {{ forloop.counter }})"
                                            class="btn btn-success fa fa-save"
                                            href="{% url 'frontsite:rhyme-store' rhyme.id %}"
                                    >
                                        Dodaj do ulubionych
                                    </a>
                                {% else %}
                                    <a
                                            ng-click="storeChange($event, '{% url 'frontsite:rhyme-store' rhyme.id %}', ' Dodaj do ulubionych', {{ forloop.counter }})"
                                            class="btn btn-success fa fa-save"
                                            href="{% url 'frontsite:rhyme-unstore' rhyme.id %}"
                                    >
                                        Wypisz się
                                    </a>
                                {% endif %}
                                {% if rhyme.author.id == request.user.profile.id or request.user.is_staff %}
                                    <a class="pull-right btn btn-primary btn-xs"
                                       ng-click="edit($event, {{ forloop.counter }})"
                                       href="{% url 'frontsite:rhyme_detail' rhyme.id %}"
                                    ><i class="fa fa-edit"></i>Edytuj
                                    </a>
                                    <a class="pull-right btn btn-primary btn-xs"
                                       ng-click="remove($event, {{ forloop.counter }})"
                                       href="{% url 'frontsite:rhyme_detail' id=rhyme.id delete='delete' %}"
                                    ><i class="fa fa-ban"></i>Usuń
                                    </a>
                                {% endif %}
                                </div>
                            {% endif %}
                            {% if rhyme.comments_count > 0 %}
                                <br />
                                <div
                                        class="pull-right"
                                        ng-controller="PopoverCommentsCtrl"
                                        ng-mouseover="popoverComments($event, {{ rhyme.id }}, '{% url 'frontsite:comment_show' rhyme.id %}')"
                                        ng-click="popoverComments($event, {{ rhyme.id }}, '{% url 'frontsite:comment_show' rhyme.id %}')"
                                >
                                    <div>
                                        <div id="popover-{{ rhyme.id }}" class="popover top">
                                            <h3 class="popover-title">Najnowsze komentarze</h3>
                                            <div class="popover-content">
                                                <div ng-repeat="comment in comments">
                                                    <div class="row-fluid">
                                                        <span class="col-md-8">
                                                            {$ comment.content $}
                                                        </span>
                                                        <span class="col-md-4 badge">{$ comment.author_name $}</span>
                                                    </div>
                                                    <hr>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <span class="text text-success">Komentarzy: </span>
                                    <label class="label label-success">{{ rhyme.comments_count }}</label>


                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% if scarfording == 2 or forloop.last %}
                    </div>
                    {% set_int_var 0 as scarfording %}
                {% endif %}
        {% endfor %}
        {% endwith %}
        </div><!-- div wrapper %}-->
        <div class="row">
            <div class="text-center pagination col-md-12">
                <span class="step-links">
                    {% if rhymes.has_previous %}
                        <a href="?page={{ rhymes.previous_page_number }}">poprzednia</a>
                    {% endif %}

                    <span class="current">
                        Strona {{ rhymes.number }} z {{ rhymes.paginator.num_pages }}.
                    </span>

                    {% if rhymes.has_next %}
                        <a href="?page={{ rhymes.next_page_number }}">następna</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript-custom %}
<script type="text/javascript" src="{% static 'frontsite/tinymce/js/tinymce/tinymce.min.js' %}"></script>
<script>
    tinyMCE.init({
        selector: "textarea",
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste"
        ],
        height : 300,
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
    });
</script>
{% endblock %}